### ISSUE TITLE
fluid capability proxy

### ISSUE THREAD

**Issue by 0Navis0** [CyclopsMC/CapabilityProxy#12]
I wondered if a proxy that could interact with fluids could be added.

**Comment by josephcsible** [comment]
Doesn't that already work?

**Comment by 0Navis0** [comment]
It's what I wondered too, if it would work with simple block capability proxy, I didn't try everything, so I couldn't tell about it.

**Comment by rubensworks** [comment]
@Hypsellis You'll have to be more concrete, not sure what you mean exactly.

**Comment by josephcsible** [comment]
Closing due to lack of response.
