### ISSUE TITLE
Server crash right-clicking on just created ranged proxy

### ISSUE THREAD

**Issue by yurikus** [CyclopsMC/CapabilityProxy#18]
#### Issue type:

- :bug: Server hard lockup and forced crash with 
```java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)```
____

#### Short description:

Made a ranged proxy, put it in the world in the open space, right-clicked it, server locked-up and was terminated, client timed out.

#### Steps to reproduce the problem:

1. Make Ranged Proxy
2. Put in the world (in an open space)
3. Right-click

#### Expected behaviour:

At most a GUI, at least a chat message along the lines of "Please shift-click on something". 
As a corollary, I can't find how to bind ranged proxy to a block. Shift-right-click, right-click, etc ? 
Now placing this block anywhere and simply looking at it locks up the server every time.
____

#### Versions:

- This mod: 2.1.2
- Minecraft:  1.12.2
- Forge: 14.23.5.2784-universal

#### Log file:

[190109-ranged-proxy-crash-reports.zip](https://github.com/CyclopsMC/CapabilityProxy/files/2741282/190109-ranged-proxy-crash-reports.zip)

**Comment by rubensworks** [comment]
Please use the issue template.

**Comment by yurikus** [comment]
Updated

**Comment by rubensworks** [comment]
Thanks :-)

**Comment by rubensworks** [comment]
I can not reproduce this myself.

Could you try reproducing this in a clean environment. Refined Storage seems to be involved in this crash.

Also, did you by any chance change the `range` config option, this should be 16 by default. Setting this to a very large value could explain this crash.

**Comment by yurikus** [comment]
haha:
`    I:ranged_capability_proxy.range=2147483640
`

**Comment by rubensworks** [comment]
Ah, there you go :-)

In any case, I'll add a note in the config option's comment to say that large values will lag/crash your game.
