### ISSUE TITLE
No automated ability to add or remove items from item capability proxy

### ISSUE THREAD

**Issue by Austin5003** [CyclopsMC/CapabilityProxy#22]
#### Issue type: 

- :bug: Bug

____

#### Short description:

The side of the item proxy where items with storage capabilities isn't recognized as a valid face to insert to or pull from

#### Steps to reproduce the problem:

1. Place item capability proxy
2. Place a hopper, modded item pipe, etc. on the side where items with capabilities are normally inserted

#### Expected behavior:

Storage items being inserted or removed accordingly

____

#### Versions:

- This mod: 2.1.4
- Minecraft: 1.14.4
- Forge: 28.1.64

#### Log file:

No crash, debug log available upon request

**Comment by rubensworks** [comment]
Right, that used to be possible in 1.12, but looks broken now.
