### ISSUE TITLE
[Incompatibility] Errors when interacting with ranged proxy

### ISSUE THREAD

**Issue by Austin5003** [CyclopsMC/CapabilityProxy#23]
#### Issue type:

- :bug: Bug

____

#### Short description:

Ranged proxies don't shut off when they can't find a tile entity, which causes modded item extractors and inserters to throw errors (i.e. simple storage network)

#### Steps to reproduce the problem:

1. Just use an item pipe from pretty much any mod on a ranged proxy when it isn't connected to another tile entity

#### Expected behavior:

Expecting ranged proxy to shut off like other proxies when it can't find anything to connect to

____

#### Versions:

- This mod: 2.1.4
- Minecraft: 1.14.4
- Forge: 28.1.64

#### Log file:

Too large for pastebin, I have to post the file here again
Since it's ultimately other mods crashing, you could simply not give a single shit and disregard this issue entirely, but making a change would be greatly appreciated
[crash-2019-10-29_04.05.05-server.txt](https://github.com/CyclopsMC/CapabilityProxy/files/3782341/crash-2019-10-29_04.05.05-server.txt)

**Comment by rubensworks** [comment]
Should be fixed in 9bd22a0503fbc744a8261afb4ce40d65738e618e.
