### ISSUE TITLE
Unable to interface with a Composter

### ISSUE THREAD

**Issue by MuteTiefling** [CyclopsMC/CapabilityProxy#24]
#### Issue type:

- :bug: Bug

____

#### Short description:

The capability proxy doesn't appear to interact with a vanilla composter. It's inactive no matter where it's pointed. Hoppers connected to the capability proxy do not push into the composter.

#### Steps to reproduce the problem:

1. Point a proxy at a vanilla composter. It doesn't light up as active and doesn't function. 

#### Expected behaviour:

Items should flow from a hopper through the proxy, to the composter.

____

#### Versions:

- This mod: CapabilityProxy-1.15.2-2.1.5
- Minecraft: 1.15.2
- Forge: 31.2.0

**Comment by rubensworks** [comment]
Hmm, weird. Does placing a hopper directly against a composter actually work?

**Comment by MuteTiefling** [comment]
Yeah. A hopper can interface with it from the top and bottom only.

For the record, I haven't gotten any modded pipes to work with the composter. Only vanilla hoppers or modded right click machines.

**Comment by rubensworks** [comment]
I assume the composter is missing a capability then, but I'll look into it.

**Comment by rubensworks** [comment]
Implemented support in the latest version, but requires the Common Capabilities mod as well.
