### ISSUE TITLE
Is there a way to clear BlockItem metadata?

### ISSUE THREAD

**Issue by rosshadden** [CyclopsMC/CapabilityProxy#25]
#### Issue type:

- :question: Question

____

#### Question:

After placing the proxies, they no longer stack. In some mods there is a way to clear the metadata to make the items as if they were just crafted. In some for example you craft the item itself and the output is the same item, but with cleared metadata. I've also experienced mods where you smelt the item to "purge" the metadata, which is pretty clever where it makes sense.

Is there a way to get these things to stack again?

**Comment by rubensworks** [comment]
Not possible at the moment unfortunately. (it is in 1.15 though)
