### ISSUE TITLE
Capability Proxy doesn't work

### ISSUE THREAD

**Issue by DraGonFiirE** [CyclopsMC/CapabilityProxy#26]
#### Issue type:

- :bug: Bug

____

#### Short description:

Capability Proxy doesn't work

#### Steps to reproduce the problem:

1. Place a chest
2. Point the Capability Proxy towards the chest and place
3. Point a hopper towards the Capability Proxy and place
4. Put an item into the hopper

#### Expected behaviour:

the item ends up in the chest

____

#### Versions:

- This mod: 1.15.2-2.1.6
- Minecraft:  1.15.2
- Forge: 31.2.45

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Do you have any other mods installed? If so, could you retry without any others?

**Comment by DraGonFiirE** [comment]
Yes I'm playing with the Enigmatica 5 modpack
Just tested with only Capability Proxy and JEI and works just fine
Time to put all the mods back in one by one to test whats causing the issue I guess

**Comment by DraGonFiirE** [comment]
This seems to be related to CommonCapabilities, once I add it it no longer works
Tried with CommonCapabilities-1.15.2-2.5.4 as well as CommonCapabilities-1.15.2-2.5.3 to no success

**Comment by rubensworks** [comment]
Thanks for checking, that helps me a lot. Will release a hotfix in a bit.

**Comment by rubensworks** [comment]
Release 2.1.7 will be out on CF soon.
