### ISSUE TITLE
Fluid duping using buckets in item capability proxy

### ISSUE THREAD

**Issue by ghost** [CyclopsMC/CapabilityProxy#28]
#### Issue type:

- :bug: Bug 

____

#### Short description:
When I set up an item capability proxy and hook it up to an integrated tunnels network through a fluid interface combined with an importer or exporter set up to clear the fluid in the container in the item capability proxy,  any fluids inside buckets in the item capability proxy don't seem to properly lose their contents. 1000 mB of fluid is still exported into the system without affecting the fluid inside the bucket. 

#### Steps to reproduce the problem:
1. Set up an Item Capability proxy
2. Connect it to an Integrated Tunnels network where it imports fluids out of the item capability proxy. 
3. Connect an empty tank to the network where said fluid will be stored.
4. Put a bucket filled with liquid inside the item capability proxy (I have tried vanilla and ID fluids so far). 
5. See that 1000 mB of fluid gets sent to the empty tank while the bucket with liquid did not get emptied.

#### Expected behaviour:
I expect fluids to get cleared when used inside an item capability proxy. Right now if I repeatedly import and export the same bucket into and out of the item capability proxy, it lets me dupe the fluid. 
____

#### Versions:

- This mod: 1.12.2-2.1.3
- Minecraft: 1.12.2
- Forge: 14.23.5.2854

I reduced my modpack to JEI, JEI Integration, TheOneProbe, TOP Addons, FTB Library/Utilities and the full Integrated Dynamics suite (including Colossal Chests)

#### Log file:
Not included since it does not crash the game.

**Comment by rubensworks** [comment]
Thanks for reporting!
