### ISSUE TITLE
Ranged Capability Proxy GUI open doesn't work from when below proxy. 

### ISSUE THREAD

**Issue by orenawesome** [CyclopsMC/CapabilityProxy#29]
#### Issue type:

- :bug: Bug 

____

#### Short description:

 

When using the ranged proxy, right clicking on it to access the GUI of the proxied block doesn't work if they player is slightly below/ above (or further below / above) the proxy. I've attached a video of the issue. 

https://streamable.com/mil0rl

https://streamable.com/dcfdv5

#### Steps to reproduce the problem:

1. Place down the block you want to proxy (I've tried it with an EnderIO Sagmill and a thermal pulverizer)

2. Go down  7-8 blocks below /above it, and place the ranged capability proxy, and point it towards the block you would like to proxy. 

3. Right click on the capability proxy, from all sides and at all angles above the proxy, it works as expected. From below/ above (respectively), it doesn't.  (Even if the OG block is right-clickable from all sides) 

4. These same steps can be repeated from above. I also have a video for that. 

#### Expected behaviour:

Right clicking anywhere on the proxy, from any player position, opens the original block gui. 
____

#### Versions:

- This mod: CapabilityProxy-1.12.2-2.1.3
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I'm sorry, but MC 1.12 is not supported anymore.
Feel free to reopen the issue if it still persists for MC 1.16.
