### ISSUE TITLE
Mimic Tile Entity NBT Data

### ISSUE THREAD

**Issue by DraGonFiirE** [CyclopsMC/CapabilityProxy#30]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

Make the Capability Proxy be able to mimic Tile Entity NBT Data so you can get some clean setups without Block Readers around a block

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
That's impossible unfortunately, as this would break world saves.

Perhaps some workaround specifically for Integrated Dynamics could be added, but this would have to be carefully thought out.

**Comment by DraGonFiirE** [comment]
And I was always wondering why other mimic mods like Entangled or Phantom Faces didnt have the option to also mimic nbt, now I know why.
Too bad, that would've been a dope feature to have
