### ISSUE TITLE
Entity capability proxy

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/CapabilityProxy#5]
#### Issue type:

_Only keep the issue types that are applicable._

- :heavy_plus_sign: Feature request

Can we add a new type of proxy block that will proxy to an entity that it points at, rather than to a block?

**Comment by rubensworks** [comment]
That does indeed sound interesting. Something similar could be done for an item proxy (inside an inventory), which is basically what EvilCraft's Display Stand already does.
